# Adapted from the scikit-learn setup
jobs:

- template: ci/azure/posix.yml
  parameters:
    name: macOS
    vmImage: xcode9-macos10.13
    matrix:
      py37:
        PYTHON_VERSION: '3.7'
      py36:
        PYTHON_VERSION: '3.6'
      py35:
        PYTHON_VERSION: '3.5'


- template: ci/azure/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
    matrix:
      py37_64:
        PYTHON_VERSION: '3.7'
      py36_64:
        PYTHON_VERSION: '3.6'
      py35_64:
        PYTHON_VERSION: '3.5'
