# Adapted from the scikit-learn setup
jobs:

- template: ci/azure/posix.yml
  parameters:
    name: macOS
    vmImage: macOS-10.14
    matrix:
      py38:
        PYTHON_VERSION: '3.8'
        PYTHON_ARCH: '64'
      py37:
        PYTHON_VERSION: '3.7'
        PYTHON_ARCH: '64'
      py36:
        PYTHON_VERSION: '3.6'
        PYTHON_ARCH: '64'

- template: ci/azure/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
    matrix:
      py38_64:
        PYTHON_VERSION: '3.8'
      py37_64:
        PYTHON_VERSION: '3.7'
      py36_64:
        PYTHON_VERSION: '3.6'
