version: 2

jobs:
  rust-stable:
    working_directory: ~/repo
    docker:
      - image: rust:1.30.1-slim-stretch
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            apt-get update
            apt-get install -y build-essential

      - run:
          name: build
          command: |
            cargo build

      - run:
          name: test
          command: |
            cargo test

  python-wrapper:
    working_directory: ~/repo
    docker:
      - image: rustlang/rust:nightly-slim
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            apt-get update
            apt-get install -y build-essential python3-pip
            cd python/
            pip3 install -e requirements.txt

      - run:
          name: build
          command: |
            cd python/
            python3 setup.py develop

      - run:
          name: test
          command: |
            pytest text_vectorize

  lint:
    working_directory: ~/repo
    docker:
      - image: rust:1.30.1-slim-stretch
    steps:
      - checkout

      - run:
          name: dependencies
          command: |
            apt-get update
            apt-get install -y python3-pip
            rustup component add rustfmt-preview
            pip3 install flake8

      - run:
          name: lint
          command: |
            cargo fmt -- --check
            flake8 python/
            cd python && cargo fmt -- --check


workflows:
  version: 2
  build:
    jobs:
      - rust-stable
      - python-wrapper
      - lint
