version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: rust:1.30.1-slim-stretch

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: build
          command: |
            cargo build

      - run:
          name: test
          command: |
            cargo test

  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: lint
          command: |
            cargo fmt -- --check

workflows:
  version: 2
  build:
    jobs:
      - build
      - lint
