version: 2

jobs:
  rust-stable:
    working_directory: ~/repo
    docker:
      - image: rust:1.30.1-slim-stretch
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            apt-get update
            apt-get install -y build-essential

      - run:
          name: build
          command: |
            cargo build

      - run:
          name: test
          command: |
            cargo test

  python-wrapper:
    working_directory: ~/repo
    docker:
      - image: rthz/rust-nightly-python37
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            python -m pip install tox
      - run:
          name: build-test
          command: |
            cd python
            tox

  lint:
    working_directory: ~/repo
    docker:
      - image: rthz/rust-nightly-python37
    steps:
      - checkout

      - run:
          name: dependencies
          command: |
            apt-get update
            rustup component add rustfmt-preview
            python -m pip install flake8 black

      - run:
          name: lint
          command: |
            cargo fmt -- --check
            flake8 --max-line-length=88 python/ benchmarks/
            black --check python/ benchmarks/
            cd python && cargo fmt -- --check


workflows:
  version: 2
  build:
    jobs:
      - rust-stable
      - python-wrapper
      - lint
