
parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    VIRTUALENV: 'testvenv'
    JUNITXML: 'test-data.xml'
    SKLEARN_SKIP_NETWORK_TESTS: '1'
    TMP_FOLDER: '$(Agent.WorkFolder)\tmp_folder'
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH for 64 bit Python
      condition: eq(variables['PYTHON_ARCH'], '64')
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        addToPath: true
        architecture: 'x86'
      displayName: Use 32 bit System Python
      condition: eq(variables['PYTHON_ARCH'], '32')
    - script: |
        ci\\azure\\install.cmd
      displayName: 'Install'
    - script: |
        ci\\azure\\test_script.cmd
      displayName: 'Test Library'
